version: '3'
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /app/firebase.json
      GOOGLE_PROJECT_ID: no-name-app-a5a97
      PYTHONUNBUFFERED: 1
